// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_r8q_il3dqxSQrudzPvcG1Gw_4LeBB_o',
    appId: '1:738147746114:web:71616a53837174f459c8db',
    messagingSenderId: '738147746114',
    projectId: 'chatapp-922b4',
    authDomain: 'chatapp-922b4.firebaseapp.com',
    storageBucket: 'chatapp-922b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2N23M03F2Q-9cfGra5dI1yGPTUDCNAZo',
    appId: '1:738147746114:android:44eb40b0fd37660459c8db',
    messagingSenderId: '738147746114',
    projectId: 'chatapp-922b4',
    storageBucket: 'chatapp-922b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuIMoWe7ePPQALumxnaN0VtP0Nuwu8idA',
    appId: '1:738147746114:ios:e30501f5f36d26e659c8db',
    messagingSenderId: '738147746114',
    projectId: 'chatapp-922b4',
    storageBucket: 'chatapp-922b4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuIMoWe7ePPQALumxnaN0VtP0Nuwu8idA',
    appId: '1:738147746114:ios:e30501f5f36d26e659c8db',
    messagingSenderId: '738147746114',
    projectId: 'chatapp-922b4',
    storageBucket: 'chatapp-922b4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_r8q_il3dqxSQrudzPvcG1Gw_4LeBB_o',
    appId: '1:738147746114:web:9f32788d6f07aa4659c8db',
    messagingSenderId: '738147746114',
    projectId: 'chatapp-922b4',
    authDomain: 'chatapp-922b4.firebaseapp.com',
    storageBucket: 'chatapp-922b4.firebasestorage.app',
  );
}
